####Section A: Data Structures & Control Structures

1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [2]:
# Creating the list of 5 integers
my_list = [10, 20, 30, 40, 50]

In [3]:
# appending the no.
my_list.append(60)
print("Append:", my_list)

Append: [10, 20, 30, 40, 50, 60]


In [4]:
# extending the no.
my_list.extend([70, 80])
print("Extend:", my_list)

Extend: [10, 20, 30, 40, 50, 60, 70, 80]


In [5]:
# inserting the element to the list 
my_list.insert(2, 25)
print("Insert:", my_list)

Insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]


In [6]:
# removing the element from the list 
my_list.remove(40)
print("Remove:", my_list)

Remove: [10, 20, 25, 30, 50, 60, 70, 80]


In [7]:
# using the pop function
my_list.pop()
print("Pop:", my_list)

Pop: [10, 20, 25, 30, 50, 60, 70]


In [8]:
# using the index 
print("Index of 30:", my_list.index(30))

Index of 30: 3


In [9]:
# count function
print("Count of 20:", my_list.count(20))

Count of 20: 1


In [10]:
# using the sort function 
my_list.sort()
print("Sort:", my_list)

Sort: [10, 20, 25, 30, 50, 60, 70]


In [11]:
# reverse
my_list.reverse()
print("Reverse:", my_list)

Reverse: [70, 60, 50, 30, 25, 20, 10]


In [12]:
# clear
my_list.clear()
print("Clear:", my_list)

Clear: []


2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [13]:
std = ("Aman","Hari","Ram")

In [14]:
std[1] = "Rahil"

TypeError: 'tuple' object does not support item assignment

Here it is giving the type error because tuples are immutable  due to this once we create the tuple we cannot add new element or remove the element to the tuple which we have created .

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [15]:
s = {1, 2, 2, 3, 4, 4}
print(s)

{1, 2, 3, 4}


This happens because set automatically removes duplicates .

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [21]:
my_dict = {
    "name":"Bhaskar Singh",
    "age":21,
    "city":"Bhopal"
}

In [22]:
my_dict

{'name': 'Bhaskar Singh', 'age': 21, 'city': 'Bhopal'}

In [23]:
#updating  the age  from the list 
my_dict["age"] = 22 

In [24]:
my_dict

{'name': 'Bhaskar Singh', 'age': 22, 'city': 'Bhopal'}

In [25]:
#adding the email to the dictionary 
my_dict["email"] = "bhaskarsingh04@gamil.com"
print(my_dict)

{'name': 'Bhaskar Singh', 'age': 22, 'city': 'Bhopal', 'email': 'bhaskarsingh04@gamil.com'}


5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [35]:
age = int(input("enter the age:"))

if  age>=18:
    print("you are eligible to vote")
else:
    print("you are not eligible")

enter the age: 56


you are eligible to vote


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [37]:
marks = int(input("enter the marks:"))

if marks>=90:
    print("A")
elif marks>=75:
    print("B")
elif marks>=50:
    print("C")
else:
    print("FAIL")

enter the marks: 98


A


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [38]:
num = 30
if num > 0:
    if num % 2 == 0:
        print("Positive and Even")
    else:
        print("Positive but Odd")
elif num == 0:
    print("Zero")
else:
    print("Negative")

Positive and Even


#####Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [39]:
import numpy as np

# scalar
scalar = np.array(5)
print("Scalar:", scalar)

Scalar: 5


In [40]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

1D Array: [1 2 3 4 5]


In [41]:
# 2D array
arr2 = np.array([[10, 20, 30], [40, 50, 60]])
print("2D Array:\n", arr2)

2D Array:
 [[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [42]:
random_arr = np.random.randint(0, 100, (4, 4))
print(random_arr)

[[76 21 77 54]
 [43 57 65 55]
 [77 24  1  9]
 [ 0  4 64 74]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [46]:
import pandas as pd

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

df = pd.DataFrame(arr, columns=["A", "B", "C"])
print(df.to_string(index=False))

 A  B  C
 1  2  3
 4  5  6
 7  8  9


#####Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [47]:
import pandas as pd

Data = {
    "Name": ["Ajay", "Billu", "Chetta", "Dj alok", "Evii", "Faluda", "Gggg", "Hello", "Ipsita", "Jjjj"],
    "Age": [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
    "City": ["Bhopal", "Indore", "Delhi", "Mumbai", "Pune", "Chennai", "Jaipur", "Goa", "Lucknow", "Nagpur"],
    "Salary": [20000, 25000, None, 30000, 35000, None, 40000, 45000, 50000, 55000]
}

df = pd.DataFrame(Data)
print(df)

      Name  Age     City   Salary
0     Ajay   20   Bhopal  20000.0
1    Billu   21   Indore  25000.0
2   Chetta   22    Delhi      NaN
3  Dj alok   23   Mumbai  30000.0
4     Evii   24     Pune  35000.0
5   Faluda   25  Chennai      NaN
6     Gggg   26   Jaipur  40000.0
7    Hello   27      Goa  45000.0
8   Ipsita   28  Lucknow  50000.0
9     Jjjj   29   Nagpur  55000.0


In [48]:
###Info & Describe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [49]:
df.describe()

,Age,Salary
count,10.00000,8.000000
mean,24.50000,37500.000000
std,3.02765,12247.448714
min,20.00000,20000.000000
25%,22.25000,28750.000000
50%,24.50000,37500.000000
75%,26.75000,46250.000000
max,29.00000,55000.000000


In [51]:
#selecting the name and city
print(df[["Name", "City"]])

      Name     City
0     Ajay   Bhopal
1    Billu   Indore
2   Chetta    Delhi
3  Dj alok   Mumbai
4     Evii     Pune
5   Faluda  Chennai
6     Gggg   Jaipur
7    Hello      Goa
8   Ipsita  Lucknow
9     Jjjj   Nagpur


In [52]:
###droping the city
df = df.drop("City", axis=1)
print(df)

      Name  Age   Salary
0     Ajay   20  20000.0
1    Billu   21  25000.0
2   Chetta   22      NaN
3  Dj alok   23  30000.0
4     Evii   24  35000.0
5   Faluda   25      NaN
6     Gggg   26  40000.0
7    Hello   27  45000.0
8   Ipsita   28  50000.0
9     Jjjj   29  55000.0


In [55]:
### filiing the missinf values 
df["Salary"].fillna(df["Salary"].mean())
print(df)

      Name  Age   Salary
0     Ajay   20  20000.0
1    Billu   21  25000.0
2   Chetta   22  37500.0
3  Dj alok   23  30000.0
4     Evii   24  35000.0
5   Faluda   25  37500.0
6     Gggg   26  40000.0
7    Hello   27  45000.0
8   Ipsita   28  50000.0
9     Jjjj   29  55000.0


In [56]:
### droping the duplicates
df = df.drop_duplicates()
print(df)

      Name  Age   Salary
0     Ajay   20  20000.0
1    Billu   21  25000.0
2   Chetta   22  37500.0
3  Dj alok   23  30000.0
4     Evii   24  35000.0
5   Faluda   25  37500.0
6     Gggg   26  40000.0
7    Hello   27  45000.0
8   Ipsita   28  50000.0
9     Jjjj   29  55000.0
